### ISSUE TITLE
English version?

### ISSUE THREAD

**Issue by DonaldTsang** [luolongfei/freenom#4]
I think I understand that this is a freenom domain registration tool, could you write an English version of the README.md?

**Comment by luolongfei** [comment]
This is not a tool for registering freenom domain names. This is a tool for automatically renewing freenom domain names. Sorry, my English is not very good, I may not write the English version of the README.md

**Comment by DonaldTsang** [comment]
@luolongfei I know Chinese, but the instructions are not too clear.

**Comment by luolongfei** [comment]
@DonaldTsang 
The following actions apply to centos7, Make sure that php is already installed on your server. You can see the php version by executing php --version.

Create a new folder called freenom and open it
$ mkdir /home/freenom && cd /home/freenom

Clone this warehouse source code
$ git clone https://github.com/luolongfei/freenom.git ./

Apply for a new gmail mailbox for the program to send notification emails

The process of applying for a gmail mailbox is omitted here. Below we set up a gmail mailbox so that it can be used by the program to send notification emails.

Log in to the gmail mailbox you just applied and click the settings icon in the upper right area of the screen.
(Generally a url like this https://mail.google.com/mail/u/0/#settings/fwdandpop, Please note that if you log in to multiple gmail accounts in the same browser, the 0 in this url may be 1 or 2. Please determine the correct url according to your actual situation.)
position: Settings -> Forwarding and POP/IMAP
Steps:
1.Check "Enable POP for all mail (even mail that's already been downloaded)"
2.Check "Enable IMAP"
3.Click on "Save Changes"

Access to less secure apps
Visit this URL:
https://myaccount.google.com/u/0/lesssecureapps?pli=1&pageId=none
(Please note that if you log in to multiple gmail accounts in the same browser, the 0 in this url may be 1 or 2. Please determine the correct url according to your actual situation.)
Please turn on "Allow less secure apps"
Allow less secure apps: Enabled

At this point, the gmail mailbox is configured.

Modify the config.php file
$ vim /home/freenom/config.php
Just need to modify the items with English comments below
return [
    'userInfo' => [
        'name' => 'Your name',
        'username' => '593198779@qq.com', // Your freenom account
        'password' => 'xxxxxx', // Your freenom password
        'userAgent' => 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36',
    ],
    'mail' => [
        'from' => 'llf.push@gmail.com', // The sender you want to display
        'to' => 'mybsdc@qq.com', // Your email address, used to receive notification emails from the program
        'replyTo' => 'mybsdc@gmail.com',
        'username' => 'llf.push@gmail.com', // Your gmail email address, Your gmail email address, the program will use this email account to send emails to the email address you use to receive notifications.
        'password' => 'xxxxxx', // Your gmail email password
        'debug' => 0,
    ],
];

Install crontabs and cronie
$ yum -y install cronie crontabs

Verify that crond is installed and started
$ yum list cronie && systemctl status crond
Verify that crontab is installed
$ yum list crontabs $$ which crontab && crontab -l

Add a crontab task
$ crontab -e
Add the following (The meaning of this task is that the index.php script is executed every day at 8 am.):
00 08 * * * cd /home/freenom/; php index.php >/dev/null 2>&1

Restart the crond daemon
$ systemctl restart crond

It’s all done here. I hope this can help you.

**Comment by vinanrra** [comment]
Does this still work?, because i would like to use it

**Comment by luolongfei** [comment]
> Does this still work?, because i would like to use it

Yes it still works.

**Comment by luolongfei** [comment]
@vinanrra Yes it still works.

**Comment by vinanrra** [comment]
This will renew my domain but can change anything at DNS?

![imagen](https://user-images.githubusercontent.com/4247187/73036879-3b81fd00-3e4d-11ea-9731-d953fd11f07b.png)

Because i would like to renew and update some DNS if my IP have change.

**Comment by luolongfei** [comment]
@vinanrra I'm sorry this script can't help you update your DNS. It is recommended that you host your domain on cloudflare. When the IP address changes, you can manually go to cloudflare and modify it ...

**Comment by DonaldTsang** [comment]
@luolongfei apologies for being off-topic but have you considered creating a nodeJS or Python alternative for this repo?

**Comment by luolongfei** [comment]
@DonaldTsang Sorry, there is no plan for this in the short term, maybe I will consider using Python to implement it in the future.

**Comment by luolongfei** [comment]
Newly added English documentation：https://github.com/luolongfei/freenom/blob/master/README_EN.md
