### ISSUE TITLE
bug_report

### ISSUE THREAD

**Issue by origamiofficial** [luolongfei/freenom#46]
**Describe the problem**
````
Docker container sends Chinese language notifications on Telegram.
````

**Steps to reproduce**
````
Add "LANGUAGE=en" in .env file
````

**Screenshots & Logs**

**What did you try**
````
I've manually downloaded the latest .env file from this repository but still, it sends Chinese notifications on Telegram.
````

**Environmental Information**
  - Ubuntu server 20.04 armhf
  - Docker image latest tag arm/v7

**Additional Notes**
- Container may be working correctly because I don't have any renewable domain.

**Comment by luolongfei** [comment]
@anjumrafidofficial 
Hi, this is because the version that supports English has not been released yet. The docker image has not been updated yet. Because there are still some things to tweak now, I will release v0.4.5 when the tweaking is done.

If you want to try v0.4.5 in advance, you can pull the source code and execute it directly.

**Comment by luolongfei** [comment]
@anjumrafidofficial 
The current English version of the email content needs to be adjusted to make it more authentic. Would you be willing to help me improve the content of the English version of the email? If so, please let me know your email address and I will send you the English version of the email.

**Comment by origamiofficial** [comment]
@luolongfei yeah sure. Here is my email address me@rafid.cf

**Comment by luolongfei** [comment]
@anjumrafidofficial Thanks a lot! I've sent you the relevant email.

**Comment by origamiofficial** [comment]
@luolongfei I've sent the English version of the files. Please check there may be some formatting issues because I'm not familiar with .eml files so I've edited them using Microsoft Word.

**Comment by luolongfei** [comment]
@anjumrafidofficial Thank you for your contribution! I've just released v0.4.5 on docker hub, which now has full support for English.

https://hub.docker.com/r/luolongfei/freenom

**Comment by luolongfei** [comment]
https://hub.docker.com/r/luolongfei/freenom

**Comment by origamiofficial** [comment]
@luolongfei Just got the notification. Thank you so much for your effort. If you need any further help just mention me, I'll be there. I have a question, how long does Freenom permit us to renew a free domain? Searched Google but found nothing.

**Comment by luolongfei** [comment]
@anjumrafidofficial freenom allows us to renew our domain name for a maximum of one year at a time, without mentioning any other restrictions, so I think we can keep renewing our domain name and use it for free forever. Unless freenom changes the renewal rules in the future.

**Comment by Mytonn** [comment]
Hi @luolongfei. Is there any ETA for English version of v0.5.1?

**Comment by luolongfei** [comment]
@Mytonn Hi, please set the value of CUSTOM_LANGUAGE in the .env file to en to enable English mode

**Comment by Mytonn** [comment]
> @Mytonn Hi, please set the value of CUSTOM_LANGUAGE in the .env file to en to enable English mode

My mistake. I think it is back to the en to ze after upgrade. Thank you.

**Comment by luolongfei** [comment]
@Mytonn In fact, the upgrade does not change back to Chinese under normal circumstances, the old configuration in the .env file will be updated automatically. This time it is mainly because I renamed the environment variable LANGUAGE to CUSTOM_LANGUAGE. Because in some cases, the variable name LANGUAGE can conflict with the system's LANGUAGE variable and cause some problems, that's why the renaming operation.
